bach_homepage:
    pattern:  /
    defaults: { _controller: AnphHomeBundle:Default:index }

bach_search:
    pattern: /search/{query_terms}/{page}
    defaults: { _controller: AnphHomeBundle:Default:index, 'query_terms': null, 'page': 1 }
    requirements:
        page: \d+

bach_do_search:
    pattern:  /do-search
    defaults: { _controller: AnphHomeBundle:Default:doSearch }

bach_browse:
    pattern: /browse/{part}
    defaults: { _controller: AnphHomeBundle:Default:browse, part: 'cSubject' }
