parameters:
   anph.home.solarium_query_factory.class: Anph\HomeBundle\Service\SolariumQueryFactory

services:
    anph.home.solarium_query_factory:
        class: "%anph.home.solarium_query_factory.class%"
        arguments: [ @solarium.client.default ]
