# Copyright (c) 2014, Anaphore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     (1) Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#     (2) Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#     (3)The name of the author may not be used to
#    endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

drivers:
    matricules:
        mapper: Bach\IndexationBundle\Entity\Mapper\MatriculesDriverMapper
        fileformat: Bach\IndexationBundle\Entity\MatriculesFileFormat
        doctrine: BachIndexationBundle:MatriculesFileFormat
        fields:
            - id
            - cote
            - date_enregistrement
            - lieu_enregistrement
            - classe
            - nom
            - prenoms
            - matricule
            - annee_naissance
            - lieu_naissance
            - start_dao
            - end_dao
            - additional_informations
    ead:
        mapper: Bach\IndexationBundle\Entity\Mapper\EADDriverMapper
        fileformat: Bach\IndexationBundle\Entity\EADFileFormat
        doctrine: BachIndexationBundle:EADFileFormat
        preprocessor:
        fields:
            eadheader:
                - eadid
                - filedesc/titlestmt/author
                - filedesc/titlestmt/titleproper
                - filedesc/publicationstmt/publisher
                - filedesc/publicationstmt/address/addressline
                - filedesc/publicationstmt/date
                - profiledesc/creation
                - profiledesc/creation/date
                - profiledesc/langusage
                - profiledesc/langusage/language
            archdesc:
                root:
                    - did/unitid
                    - did/unittitle
                    - did/unitdate|did/unittitle/unitdate
                    - did/physdesc
                    - did/repository
                    - did/langmaterial
                    - did/origination
                    - acqinfo
                    - scopecontent
                    - accruals
                    - arrangement
                    - accessrestrict
                    - accessrestrict//legalstatus[1]
                    - userestrict
                    - originalsloc
                    - relatedmaterial
                    - odd
                    - processinfo/processinfo
                    - controlaccess
                c:
                    - did/unitid
                    - did/unittitle
                    - did/unitdate|did/unittitle/unitdate
                    - did/physdesc
                    - did/repository
                    - did/langmaterial
                    - did/origination
                    - scopecontent
                    - controlacces
                    - .//daoloc|.//dao|.//archref[not(contains(@href, 'http://')) and contains(@href, '.pdf')]
                    - .//controlaccess//corpname
                    - .//controlaccess//famname
                    - .//controlaccess//genreform
                    - .//controlaccess//geogname
                    - .//controlaccess//name
                    - .//controlaccess//persname
                    - .//controlaccess//subject
                    - .//controlaccess//title
                    - .//controlaccess//function
                    - accessrestrict//legalstatus[1]
                    - .//controlaccess//geogname[@latitude and @longitude]

