drivers:
    ead:
        mapper: Bach\IndexationBundle\Entity\Mapper\EADDriverMapper
        universalfileformat: Bach\IndexationBundle\Entity\UniversalFileFormat\EADFileFormat
        preprocessor:
        fields:
            eadheader:
                - eadid
                - filedesc/titlestmt/author
                - filedesc/titlestmt/titleproper
                - filedesc/publicationstmt/publisher
                - filedesc/publicationstmt/address/addressline
                - filedesc/publicationstmt/date
                - profiledesc/creation
                - profiledesc/creation/date
                - profiledesc/langusage
                - profiledesc/langusage/language
            archdesc:
                root:
                    - did/unitid
                    - did/unittitle
                    - did/unitdate
                    - did/physdesc
                    - did/repository
                    - did/langmaterial
                    - did/origination
                    - acqinfo
                    - scopecontent
                    - accruals
                    - arrangement
                    - accessrestrict
                    - accessrestrict/legalstatus
                    - userestrict
                    - originalsloc
                    - relatedmaterial
                    - odd
                    - processinfo/processinfo
                    - controlaccess
                c:
                    - did/unitid
                    - did/unittitle
                    - did/unitdate
                    - did/physdesc
                    - did/repository
                    - did/langmaterial
                    - did/origination
                    - scopecontent
                    - controlacces
                    - daogrp/daoloc
                    - .//corpname
                    - .//famname
                    - .//genreform
                    - .//geogname
                    - .//name
                    - .//persname
                    - .//subject
    unimarc:
        mapper: Bach\IndexationBundle\Entity\Mapper\UNIMARCDriverMapper
        #universalfileformat: Bach\IndexationBundle\Entity\UniversalFileFormat\UNIMARCFileFormat
