bach_indexation_homepage:
    pattern:  /{page}
    defaults: { _controller: BachIndexationBundle:Default:index, page: 1 }

bach_indexation_queue:
    pattern:  /queue
    defaults: { _controller: BachIndexationBundle:Default:queue }

bach_indexation_upload_process:
    pattern:  /uploadProcess
    defaults: { _controller: BachIndexationBundle:Default:indexProcess }
    requirements:
        _method:  POST

bach_indexation_purge:
    pattern:  /purge
    defaults: { _controller: BachIndexationBundle:Default:purge }

bach_indexation_deletedocuments:
    pattern:  /remove
    defaults: { _controller: BachIndexationBundle:Default:removeDocuments }
    requirements:
        _method: POST

bach_indexation_empty:
    pattern:  /empty
    defaults: { _controller: BachIndexationBundle:Default:empty }

bach_indexation_add:
    pattern: /add
    defaults: { _controller: BachIndexationBundle:Default:add }

bach_eaddtd_validate:
    pattern: /validate/ead/{docid}/{ajax}
    defaults: { _controller BachIndexationBundle:Default:validateDocument, ajax: false, type: 'ead' }
