parameters:
    bach_indexation_file_driver_manager.class: Bach\IndexationBundle\Service\FileDriverManager
    bach_indexation_data_bag_factory.class: Bach\IndexationBundle\Service\DataBagFactory
    bach_indexation_universal_file_format_factory.class: Bach\IndexationBundle\Service\UniversalFileFormatFactory
    bach_indexation_pre_processor_factory.class: Bach\IndexationBundle\Service\PreProcessorFactory
    bach_indexation_process_arch_file_integration.class: Bach\IndexationBundle\Service\ArchFileIntegration
    bach_indexation_typesfiles.class: Bach\IndexationBundle\Service\TypesFiles
    bach_indexation_documenttype.class: Bach\IndexationBundle\Form\Type\DocumentType

services:
    bach.indexation.file_driver_manager:
        class: "%bach_indexation_file_driver_manager.class%"
        arguments: [ @bach.indexation.universal_file_format_factory, @bach.indexation.pre_processor_factory ]
    bach.indexation.data_bag_factory:
        class: "%bach_indexation_data_bag_factory.class%"
    bach.indexation.universal_file_format_factory:
        class: "%bach_indexation_universal_file_format_factory.class%" 
    bach.indexation.pre_processor_factory:
        class: "%bach_indexation_pre_processor_factory.class%"
        arguments: [ @bach.indexation.data_bag_factory ]
    bach.indexation.process.arch_file_integration:
        class: "%bach_indexation_process_arch_file_integration.class%"
        arguments: [ @bach.indexation.file_driver_manager, @bach.indexation.data_bag_factory, @doctrine.orm.entity_manager ]
    bach.indexation.typesfiles:
        class: '%bach_indexation_typesfiles.class%'
        arguments: [ '%bach.types%', '%bach.typespaths%' ]

    bach.indexation.form.type.document:
        class: '%bach_indexation_documenttype.class%'
        arguments: [ '%bach.types%' ]
        tags:
            - { name: form.type, alias: document}
