# Copyright (c) 2014, Anaphore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     (1) Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#     (2) Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#     (3)The name of the author may not be used to
#    endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

services:
    sonata.admin.expos:
        class: Bach\ExposBundle\Admin\ExpositionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Virtual expositions", label: "Expositions", label_catalogue: "ExposBundle" }
        arguments:
            - ~
            - Bach\ExposBundle\Entity\Exposition
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

    sonata.admin.rooms:
        class: Bach\ExposBundle\Admin\RoomAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Virtual expositions", label: "Rooms", label_catalogue: "ExposBundle" }
        arguments:
            - ~
            - Bach\ExposBundle\Entity\Room
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

    sonata.admin.panels:
        class: Bach\ExposBundle\Admin\PanelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Virtual expositions", label: "Panels", label_catalogue: "ExposBundle" }
        arguments:
            - ~
            - Bach\ExposBundle\Entity\Panel
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

    sonata.admin.documents:
        class: Bach\ExposBundle\Admin\DocumentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Virtual expositions", label: "Documents", label_catalogue: "ExposBundle" }
        arguments:
            - ~
            - Bach\ExposBundle\Entity\Document
            - 'PixSortableBehaviorBundle:SortableAdmin'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

