administration_homepage:
    pattern: /administration
    defaults: { _controller: AdministrationBundle:Default:index }
administration_dashboard:
    pattern: /dashboard
    defaults: { _controller: AdministrationBundle:Default:dashboard }
administration_fields:
    pattern: /fields
    defaults: { _controller: AdministrationBundle:Fields:refresh }
administration_fieldstype:
    pattern:  /fieldstype
    defaults: { _controller: AdministrationBundle:Types:refresh }
administration_dynamicfields:
    pattern:  /dynamicfields
    defaults: { _controller: AdministrationBundle:DynamicFields:refresh }
administration_copyfields:
    pattern: /copyfields
    defaults: { _controller: AdministrationBundle:CopyFields:refresh }
administration_uniquekey:
    pattern:  /uniquekey
    defaults: { _controller: AdministrationBundle:UniqueKey:refresh }
administration_analyzers:
    pattern:  /analyzers
    defaults: { _controller: AdministrationBundle:Analyzers:refresh }
administration_performance:
    pattern:  /performance
    defaults: { _controller: AdministrationBundle:Default:performance }
administration_coreadmin:
    pattern:  /coreadmin
    defaults: { _controller: AdministrationBundle:Default:coreadmin }
administration_fiel:
    pattern:  /fiel
    defaults: { _controller: AdministrationBundle:Default:contact }
