administration_dashboard:
    pattern: /administration/dashboard
    defaults: { _controller: AdministrationBundle:Default:dashboard }
administration_fields:
    pattern: /administration/fields
    defaults: { _controller: AdministrationBundle:Fields:refresh }
administration_fields_submit:
    pattern: /fields/submit
    defaults: { _controller: AdministrationBundle:Fields:submit }
administration_fieldstype:
    pattern:  /fieldstype
    defaults: { _controller: AdministrationBundle:Types:refresh }
administration_dynamicfields:
    pattern:  /dynamicfields
    defaults: { _controller: AdministrationBundle:DynamicFields:refresh }
administration_dynamicfields_submit:
    pattern:  /dynamicfields/submit
    defaults: { _controller: AdministrationBundle:DynamicFields:submit }
administration_copyfields:
    pattern: /copyfields
    defaults: { _controller: AdministrationBundle:CopyFields:refresh }
administration_copyfields_submit:
    pattern: /copyfields/submit
    defaults: { _controller: AdministrationBundle:CopyFields:submit }
administration_uniquekey:
    pattern:  /uniquekey
    defaults: { _controller: AdministrationBundle:UniqueKey:refresh }
administration_analyzers:
    pattern:  /analyzers
    defaults: { _controller: AdministrationBundle:Analyzers:refresh }
administration_analyzers_submit:
    pattern:  /analyzers/submit
    defaults: { _controller: AdministrationBundle:Analyzers:submit }
administration_performance:
    pattern:  /performance/index
    defaults: { _controller: AdministrationBundle:Performance:refresh }  
administration_coreadmin:
    pattern:  /coreadmin
    defaults: { _controller: AdministrationBundle:CoreAdmin:refresh }
administration_core_creation:
    pattern: /coreadmin/create
    defaults: { _controller: AdministrationBundle:CoreAdmin:createCore }
administration_fiel:
    pattern:  /fiel
    defaults: { _controller: AdministrationBundle:Default:contact }
administration_indexer:
    pattern:  /indexer
    defaults: { _controller: AdministrationBundle:Indexer:indexer }
