parameters:
    administration.xmlimport.class: Anph\AdministrationBundle\Service\XMLImport

services:
    anph.administration.xmlimport:
         class: %administration.xmlimport.class%
         arguments: [ @doctrine.orm.entity_manager ]
