parameters:
#    administration.example.class: Anph\AdministrationBundle\Example

services:
#    administration.example:
#        class: %administration.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
