# Copyright (c) 2014, Anaphore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     (1) Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#     (2) Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#     (3)The name of the author may not be used to
#    endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

services:
    sonata.admin.facets:
        class: Bach\HomeBundle\Admin\FacetsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Facets" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\Facets
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - @bach.administration.configreader
            - '%solr_search_core%'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

    sonata.admin.browsefields:
        class: Bach\HomeBundle\Admin\BrowseFieldsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Browse fields" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\BrowseFields
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - @bach.administration.configreader
            - '%solr_search_core%'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

    sonata.admin.geoloc:
        class: Bach\HomeBundle\Admin\GeolocAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Geolocalization" }
        arguments:
            - ~
            - Bach\IndexationBundle\Entity\Geoloc
            - BachHomeBundle:GeolocAdmin
        calls:
            - [ setTemplate, [edit, BachHomeBundle:Admin:edit_wmap.html.twig] ]

    sonata.admin.comment:
        class: Bach\HomeBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Comments" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\Comment
            - BachHomeBundle:CommentAdmin

    sonata.admin.tagcloud:
        class: Bach\HomeBundle\Admin\TagCloudAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Tag cloud" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\TagCloud
            - BachHomeBundle:TagCloudAdmin
            - @bach.administration.configreader
            - '%solr_search_core%'

    sonata.admin.geolocfields:
        class: Bach\HomeBundle\Admin\GeolocFieldsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Geolocalization fields" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\GeolocMainFields
            - BachHomeBundle:GeolocFieldsAdmin
            - @bach.administration.configreader
            - '%solr_search_core%'
            - Bach\IndexationBundle\Entity\EADFileFormat

    sonata.admin.matricules.geolocfields:
        class: Bach\HomeBundle\Admin\GeolocFieldsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Geolocalization fields (matricules)" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\GeolocMatriculesFields
            - BachHomeBundle:GeolocFieldsAdmin
            - @bach.administration.configreader
            - '%matricules_corename%'
            - Bach\IndexationBundle\Entity\MatriculesFileFormat

