services:
    sonata.admin.facets:
        class: Bach\HomeBundle\Admin\FacetsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Facets" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\Facets
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - @bach.administration.configreader
            - '%solr_search_core%'
        calls:
            - [ setTranslationDomain, [BachHomeBundle]]
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]
    sonata.admin.geoloc:
        class: Bach\HomeBundle\Admin\GeolocAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Geolocalization" }
        arguments:
            - ~
            - Bach\IndexationBundle\Entity\Geoloc
            - ~
        calls:
            - [ setTemplate, [edit, BachHomeBundle:Admin:edit_wmap.html.twig] ]
            - [ setTranslationDomain, [BachHomeBundle]]

    sonata.admin.comment:
        class: Bach\HomeBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Comments" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\Comment
            - BachHomeBundle:CommentAdmin
        calls:
            - [ setTranslationDomain, [BachHomeBundle]]

