services:
    sonata.admin.facets:
        class: Bach\HomeBundle\Admin\FacetsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Facets" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\Facets
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - @bach.administration.configreader
            - '%solr_search_core%'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

    sonata.admin.browsefields:
        class: Bach\HomeBundle\Admin\BrowseFieldsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Browse fields" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\BrowseFields
            - 'PixSortableBehaviorBundle:SortableAdmin'
            - @bach.administration.configreader
            - '%solr_search_core%'
        calls:
            - [ setContainer, [@service_container] ]
            - [ setPositionService, [@pix_sortable_behavior.position] ]

    sonata.admin.geoloc:
        class: Bach\HomeBundle\Admin\GeolocAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Geolocalization" }
        arguments:
            - ~
            - Bach\IndexationBundle\Entity\Geoloc
            - BachHomeBundle:GeolocAdmin
        calls:
            - [ setTemplate, [edit, BachHomeBundle:Admin:edit_wmap.html.twig] ]

    sonata.admin.comment:
        class: Bach\HomeBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Comments" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\Comment
            - BachHomeBundle:CommentAdmin

    sonata.admin.tagcloud:
        class: Bach\HomeBundle\Admin\TagCloudAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Tag cloud" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\TagCloud
            - BachHomeBundle:TagCloudAdmin
            - @bach.administration.configreader
            - '%solr_search_core%'

    sonata.admin.geolocfields:
        class: Bach\HomeBundle\Admin\GeolocFieldsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Geolocalization fields" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\GeolocMainFields
            - BachHomeBundle:GeolocFieldsAdmin
            - @bach.administration.configreader
            - '%solr_search_core%'
            - Bach\IndexationBundle\Entity\EADFileFormat

    sonata.admin.matricules.geolocfields:
        class: Bach\HomeBundle\Admin\GeolocFieldsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Search", label: "Geolocalization fields (matricules)" }
        arguments:
            - ~
            - Bach\HomeBundle\Entity\GeolocMatriculesFields
            - BachHomeBundle:GeolocFieldsAdmin
            - @bach.administration.configreader
            - '%matricules_corename%'
            - Bach\IndexationBundle\Entity\MatriculesFileFormat

