bach_homepage:
    pattern:  /
    defaults: { _controller: BachHomeBundle:Default:index }

bach_search:
    pattern: /search/{query_terms}/{page}/{facet_name}
    defaults: { _controller: BachHomeBundle:Default:search, 'query_terms': null, 'page': 1, 'facet_name': null }
    requirements:
        page: \d+

bach_do_search:
    pattern:  /do-search
    defaults: { _controller: BachHomeBundle:Default:doSearch }

bach_browse:
    pattern: /browse/{part}/{show_all}/{ajax}
    defaults: { _controller: BachHomeBundle:Default:browse, part: '', 'show_all': false, 'ajax': false }

bach_suggest:
    pattern: /suggest
    defaults: { _controller: BachHomeBundle:Default:doSuggest }

bach_matricules_suggest:
    pattern: /matricules/suggest
    defaults: { _controller: BachHomeBundle:Matricules:doSuggest }

bach_display_document_paginate:
    pattern: /show/{docid}/{page}/{ajax}
    defaults: { _controller BachHomeBundle:Default:displayDocument, page: 1, ajax: false }
    requirements:
        _method: GET
        page: \d+

bach_display_document:
    pattern: /show/{docid}/{ajax}
    defaults: { _controller BachHomeBundle:Default:displayDocument, ajax: false }
    requirements:
        _method: GET

bach_get_cover:
    pattern: /file/covers/{name}
    defaults: { _controller BachHomeBundle:Files:getCover }
    requirements:
        name: '.+'

bach_get_file:
    pattern: /file/{type}/{name}
    defaults: { _controller BachHomeBundle:Files:getFile }
    requirements:
        type: video|music|image|misc
        name: '.+'

bach_fullfacet:
    pattern: /fullfacet/{query_terms}/{name}
    defaults: { _controller: BachHomeBundle:Default:fullFacet }

bach_geozones:
    pattern: /geo/zones/{bbox}
    defaults: {_controller: BachHomeBundle:Default:getZones}

bach_add_comment:
    pattern: /comment/{docid}/add/{ajax}
    defaults: { _controller: BachHomeBundle:Comments:add, ajax: false }

bach_classification:
    pattern: /classification-scheme
    defaults: { _controller: BachHomeBundle:Default:cdc }

bach_toponym_geoloc:
    pattern: /geoloc/toponym/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:toponym }

bach_raw_geoloc:
    pattern: /geoloc/raw/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:raw }

bach_store_geoloc:
    pattern: /geoloc/store
    defaults: { _controller: BachHomeBundle:Geoloc:store }

bach_remove_geoloc:
    pattern: /geoloc/remove/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:remove }

bach_matricules:
    pattern:  /matricules
    defaults: { _controller: BachHomeBundle:Matricules:index }

bach_matricules_search:
    pattern: /matricules/search/{query_terms}/{page}/{facet_name}
    defaults: { _controller: BachHomeBundle:Matricules:search, 'query_terms': null, 'page': 1, 'facet_name': null }
    requirements:
        page: \d+

bach_matricules_fullfacet:
    pattern: /matricules/fullfacet/{query_terms}/{name}
    defaults: { _controller: BachHomeBundle:Matricules:fullFacet }

bach_matricules_do_search:
    pattern:  /matricules-do-search
    defaults: { _controller: BachHomeBundle:Matricules:doSearch }

bach_ead_html:
    pattern: /document/{docid}/{expanded}
    defaults: { _controller: BachHomeBundle:Default:eadHtml, 'expanded': false }

#this one *MUST* be last
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: BachHomeBundle:Default:removeTrailingSlash }
    requirements:
        url: .*/$
        _method: GET
