bach_homepage:
    pattern:  /
    defaults: { _controller: BachHomeBundle:Default:index }

bach_search:
    pattern: /search/{query_terms}/{page}
    defaults: { _controller: BachHomeBundle:Default:index, 'query_terms': null, 'page': 1 }
    requirements:
        query_terms: .+
        page: \d+

bach_do_search:
    pattern:  /do-search
    defaults: { _controller: BachHomeBundle:Default:doSearch }

bach_browse:
    pattern: /browse/{part}/{show_all}
    defaults: { _controller: BachHomeBundle:Default:browse, part: 'cSubject', 'show_all': false }

bach_suggest:
    pattern: /suggest
    defaults: { _controller: BachHomeBundle:Default:doSuggest }

