bach_homepage:
    pattern:  /
    defaults: { _controller: BachHomeBundle:Default:index }

bach_search:
    pattern: /search/{query_terms}/{page}
    defaults: { _controller: BachHomeBundle:Default:index, 'query_terms': null, 'page': 1 }
    requirements:
        page: \d+

bach_do_search:
    pattern:  /do-search
    defaults: { _controller: BachHomeBundle:Default:doSearch }

bach_browse:
    pattern: /browse/{part}/{show_all}/{ajax}
    defaults: { _controller: BachHomeBundle:Default:browse, part: '', 'show_all': false, 'ajax': false }

bach_suggest:
    pattern: /suggest
    defaults: { _controller: BachHomeBundle:Default:doSuggest }

bach_display_document_paginate:
    pattern: /show/{docid}/{page}/{ajax}
    defaults: { _controller BachHomeBundle:Default:displayDocument, page: 1, ajax: false }
    requirements:
        _method: GET
        page: \d+

bach_display_document:
    pattern: /show/{docid}/{ajax}
    defaults: { _controller BachHomeBundle:Default:displayDocument, ajax: false }
    requirements:
        _method: GET

bach_get_cover:
    pattern: /file/covers/{name}
    defaults: { _controller BachHomeBundle:Files:getCover }
    requirements:
        name: '.+'

bach_get_file:
    pattern: /file/{type}/{name}
    defaults: { _controller BachHomeBundle:Files:getFile }
    requirements:
        type: video|music|image|misc
        name: '.+'

bach_fullfacet:
    pattern: /fullfacet/{query_terms}/{facet_name}/{ajax}
    defaults: { _controller: BachHomeBundle:Default:index, 'query_terms': null, 'facet_name': null, 'ajax': false }

bach_geozones:
    pattern: /geo/zones/{bbox}
    defaults: {_controller: BachHomeBundle:Default:getZones}

bach_add_comment:
    pattern: /comment/{docid}/add
    defaults: { _controller: BachHomeBundle:Comments:add }

bach_classification:
    pattern: /classification-scheme
    defaults: { _controller: BachHomeBundle:Default:cdc }

bach_toponym_geoloc:
    pattern: /geoloc/toponym/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:toponym }

bach_raw_geoloc:
    pattern: /geoloc/raw/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:raw }

bach_store_geoloc:
    pattern: /geoloc/store
    defaults: { _controller: BachHomeBundle:Geoloc:store }

bach_remove_geoloc:
    pattern: /geoloc/remove/{name}
    defaults: { _controller: BachHomeBundle:Geoloc:remove }

bach_matricules:
    pattern: /matricules/{query_terms}/{page}
    defaults: { _controller: BachHomeBundle:Matricules:index, 'query_terms': null, 'page': 1 }
    requirements:
        page: \d+

bach_matricules_do_search:
    pattern:  /matricules-do-search
    defaults: { _controller: BachHomeBundle:Matricules:doSearch }

