bach_homepage:
    pattern:  /
    defaults: { _controller: BachHomeBundle:Default:index }

bach_search:
    pattern: /search/{query_terms}/{page}
    defaults: { _controller: BachHomeBundle:Default:index, 'query_terms': null, 'page': 1 }
    requirements:
        page: \d+

bach_do_search:
    pattern:  /do-search
    defaults: { _controller: BachHomeBundle:Default:doSearch }

bach_browse:
    pattern: /browse/{part}/{show_all}/{ajax}
    defaults: { _controller: BachHomeBundle:Default:browse, part: 'cSubject', 'show_all': false, 'ajax': false }

bach_suggest:
    pattern: /suggest
    defaults: { _controller: BachHomeBundle:Default:doSuggest }

bach_display_document:
    pattern: /show/{docid}/{ajax}
    defaults: { _controller BachHomeBundle:Default:displayDocument, ajax: false }
    requirements:
        _method: GET

bach_get_file:
    pattern: /file/{type}/{name}
    defaults: { _controller BachHomeBundle:Files:getFile }
    requirements:
        type: video|music|image|misc
        name: '.+'

bach_fullfacet:
    pattern: /fullfacet/{query_terms}/{facet_name}/{ajax}
    defaults: { _controller: BachHomeBundle:Default:index, 'query_terms': null, 'facet_name': null, 'ajax': false }
