parameters:
   bach.home.solarium_query_factory.class: Bach\HomeBundle\Service\SolariumQueryFactory

services:
    bach.home.solarium_query_factory:
        class: "%bach.home.solarium_query_factory.class%"
        arguments: [ @solarium.client.default ]

    bach.matricules.solarium_query_factory:
        class: "%bach.home.solarium_query_factory.class%"
        arguments: [ @solarium.client.matricules ]

    bach.home.display_ead_fragment:
        class: Bach\HomeBundle\Twig\DisplayEADFragment
        arguments: [ @router ]
        calls:
            - [setRequest, ['@?request=']]
            - [setViewer, ['%viewer_uri%']]
            - [setCoversDir, ['%covers_dir%']]
        tags:
            - { name: twig.extension }
    bach.home.display_dao:
        class: Bach\HomeBundle\Twig\DisplayDao
        arguments: [ @router, '%viewer_uri%', '%covers_dir%' ]
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: twig.extension }

    bach.home.openid_user_manager:
        class: Bach\HomeBundle\Entity\OpenIdUserManager
        arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]

    bach.home.display_cdc:
        class: Bach\HomeBundle\Twig\DisplayCdc
        arguments: [ @router, '%cdc_path%' ]
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: twig.extension }
