parameters:
   bach.home.solarium_query_factory.class: Bach\HomeBundle\Service\SolariumQueryFactory

services:
    bach.home.solarium_query_factory:
        class: "%bach.home.solarium_query_factory.class%"
        arguments: [ @solarium.client.default ]
