parameters:
   bach.home.solarium_query_factory.class: Bach\HomeBundle\Service\SolariumQueryFactory

services:
    bach.home.solarium_query_factory:
        class: "%bach.home.solarium_query_factory.class%"
        arguments: [ @solarium.client.default ]
    bach.home.display_ead_fragment:
        class: Bach\HomeBundle\Twig\DisplayEADFragment
        arguments: [ @router ]
        calls:
            - [setRequest, ['@?request=']]
            - [setViewer, ['%viewer_uri%']]
        tags:
            - { name: twig.extension }
    bach.home.display_dao:
        class: Bach\HomeBundle\Twig\DisplayDao
        arguments: [ @router, '%viewer_uri%' ]
        calls:
            - [setRequest, ['@?request=']]
        tags:
            - { name: twig.extension }
