imports:
    - { resource: config.yml }

framework:
    router:   { resource: "%kernel.root_dir%/config/routing_dev.yml" }
    profiler: { only_exceptions: false }
    templating:
        assets_base_urls: /

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        firephp:
            type:  firephp
            level: info

assetic:
    use_controller: true

#swiftmailer:
#    delivery_address: me@example.com

atoum:
    bundles:
        BachHomeBundle: ~
        BachIndexationBundle: ~

jns_xhprof:
    location_lib:    /usr/share/xhprof/xhprof_lib/utils/xhprof_lib.php
    location_runs:   /usr/share/xhprof/xhprof_lib/utils/xhprof_runs.php
    location_config: /usr/shar/xhprof/xhprof_lib/config.php
    location_web:    http://localhost/xhprof
    enabled:         true

web_profiler_extra:
    routing:
        enabled:        true
        display_in_wdt: true
    container:
        enabled:        true
        display_in_wdt: true
    assetic:
        enabled:        true
        display_in_wdt: true
    twig:
        enabled:        true
        display_in_wdt: true
