imports:
    - { resource: defaults_parameters.yml }
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @BachHomeBundle/Resources/config/admin.yml}
    - { resource: @ExposBundle/Resources/config/admin.yml}

framework:
    translator:      { fallback: "en" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    session:         ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #cache: false
    globals:
        lang: '%locale%'
        openid: '%openid_enabled%'
        expos: '%show_expos%'
        cdc: '%has_cdc%'
        show_tagcloud: '%show_tagcloud%'
        client_code: '%client_code%'
        matricules: '%has_matricules%'
        enable_social: '%enable_social%'
        tiles_url: '%tiles_url%'
        tiles_attribution: '%tiles_attribution%'
        tiles_subdomains: '%tiles_subdomains%'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
#        yui_css:
#            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar'
#        yui_js:
#            jar: '%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        logging:  "%kernel.debug%"
        profiling: "%kernel.debug%"
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Solarium Configuration
nelmio_solarium:
    clients:
        default:
            client_class: Solarium\Client
            adapter_class: Solarium\Core\Client\Adapter\Http
            endpoints: [default]
        ead:
            client_class: Solarium\Client
            adapter_class: Solarium\Core\Client\Adapter\Http
            endpoints: ead
        unimarc:
            client_class: Solarium\Client
            adapter_class: Solarium\Core\Client\Adapter\Http
            endpoints: unimarc
        matricules:
            client_class: Solarium\Client
            adapter_class: Solarium\Core\Client\Adapter\Http
            endpoints: matricules

    endpoints:
        default:
            host: '%solr_host%'
            port: '%solr_port%'
            path: '%solr_path%'
            core: '%solr_search_core%'
            timeout: 5
        ead:
            host: '%solr_host%'
            port: '%solr_port%'
            path: '%solr_path%'
            core: '%ead_corename%'
            timeout: 5
        unimarc:
            host: '%solr_host%'
            port: '%solr_port%'
            path: '%solr_path%'
            core: '%unimarc_corename%'
            timeout: 5
        matricules:
            host: '%solr_host%'
            port: '%solr_port%'
            path: '%solr_path%'
            core: '%matricules_corename%'
            timeout: 5

bach_indexation:
    types:
        - ead
        - unimarc
        - matricules
    paths:
        ead: '%ead_files_path%'
        unimarc: '%unimarc_files_path%'
        matricules: '%matricules_files_path%'

fos_user:
    db_driver: orm
    firewall_name: secured_area
    user_class: Application\Sonata\UserBundle\Entity\User
    profile:
        form:
            type: fos_user_profile
            handler: fos_user.profile.form.handler.default
            name: fos_user_profile_form
            validation_groups: [Authentication]

fp_open_id:
    db_driver: orm
    identity_class: Bach\HomeBundle\Entity\OpenIdIdentity

sonata_block:
    default_contexts: [cms]
    blocks:
        #Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    title: Super Admin
    title_logo: /img/logo.png
    security:
        handler: sonata.admin.security.handler.role

sonata_user:
    security_acl: false
    class:
        user: Application\Sonata\UserBundle\Entity\User
        group: Application\Sonata\UserBundle\Entity\Group

    profile:
        form:
            type: sonata_user_profile
            #handler: sonata_user.profile.form.handler.default
            name: sonata_user_profile_form
            validation_groups: [Profile]
    impersonating_route: bach_homepage

#lsw_memcache:
#    session:
#        client: bach
#    doctrine:
#        metadata_cache:
#            client: bach
#            entity_manager: bach          # the name of your entity_manager connection
#            document_manager: bach        # the name of your document_manager connection
#        result_cache:
#            client: bach
#            entity_manager: [bach, read]  # you may specify multiple entity_managers
#            prefix: "result_"                # you may specify a prefix for the entries
#        query_cache:
#            client: bach
#            entity_manager: bach
#    clients:
#        bach:
#            hosts:
#              - { dsn: localhost, port: 11211 }

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            sortable: true

ivory_ck_editor:
    configs:
        #full edit configuration, for Expos contents
        bach_full_edit:
            toolbar: 'bach_full_toolbar'
            uiColor: '#a3968d'
            filebrowserBrowseRoute: elfinder
        #head edit configuration, lighter, for Expos briefs descriptions
        bach_head_edit:
            toolbar: 'bach_head_toolbar'
            uiColor: '#a3968d'
            filebrowserBrowseRoute: elfinder
        #Comments configuration
        bach_comment_edit:
            toolbar: 'bach_comment_toolbar'
            uiColor: '#a3968d'
    toolbars:
        configs:
            bach_head_toolbar: [ '@head_paragraph', '-', '@basicstyles', '-',  '@head_links', '@insert', '@editing', '-', '@document', '-', '@head_tools' ]
            bach_full_toolbar: [ '@styles', '-', '@colors', '-', '@basicstyles', '-', '@links', '/', '@paragraph', '-', '@insert', '-', '@clipboard', '/', '@editing', '-', '@document', '-', '@tools' ]
            bach_comment_toolbar: [ '@head_paragraph', '-', '@basicstyles', '-',  '@head_links', '@editing', '-', '@head_tools' ]
        items:
            styles: [ 'Styles', 'Format', 'Font', 'FontSize']
            colors: [ 'TextColor', 'BGColor']
            basicstyles: [ 'Bold','Italic','Underline','Strike','Subscript','Superscript','-','RemoveFormat' ]
            clipboard: [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo' ]
            paragraph: [ 'NumberedList','BulletedList','-','Outdent','Indent','-','Blockquote','CreateDiv','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ]
            head_paragraph: [ 'NumberedList','BulletedList','-','Blockquote','-','JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock' ]
            links: [ 'Link', 'Unlink', 'Anchor' ]
            head_links: [ 'Link', 'Unlink' ]
            insert: [ 'Image', 'Table', 'HorizontalRule', 'SpecialChar' ]
            editing: [ 'Find','Replace','-','SelectAll','-','SpellChecker', 'Scayt' ]
            document: [ 'Source', '-', 'Templates' ]
            tools: [ 'Maximize', 'ShowBlocks' ]
            head_tools: [ 'Maximize' ]

fm_elfinder:
    editor: ckeditor
    connector:
        roots:
            uploads:
                path: uploads/media

services:
    bach.twig.asset_exists:
        class: Bach\HomeBundle\Twig\AssetExists
        arguments: [ @kernel ]
        tags:
            - { name: twig.extension }

