imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    templating:
        assets_base_urls: /

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

jns_xhprof:
    enabled: false

security:
    firewalls:
        secured_area:
            http_basic:
