parameters:
    #Main URL. Required for sitemaps
    bach_url: http://localhost

    #database parameters
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: bach
    database_user: bach
    database_password: A_PASSWORD
    database_path: null

    #application locale
    locale: en
    secret: fcfe28f4f96b6167f7e541210b30616ac #Usefull?

    #Solr parameters
    solr_ssl: false
    solr_host: localhost
    solr_port: 8080
    solr_path: /solr
    #Core names for each type
    ead_corename: ead
    matricules_corename: matricules
    #Default search core
    solr_search_core: '%ead_corename%'

    #Path to store uploaded files (from web publication)
    upload_dir: '%kernel.root_dir%/../web/uploads/'

    #Path to files for each type
    ead_files_path: null
    matricules_files_path: null

    ##Features activation
    #main features
    feature.cdc: false
    feature.matricules: false
    feature.expos: false
    feature.browse: true
    #display features
    feature.maps: true
    feature.tagcloud: true
    #other
    feature.openid: false
    feature.social: false
    feature.register: false

    #UI parameters
    viewer_uri: http://viewer.localhost/
    covers_dir: '%kernel.root_dir%/../web/covers/'
    cdc_path: '%kernel.root_dir%/../cdc.xml'
    tiles_url: 'http://{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpg'
    tiles_attribution: '<a href="http://www.mapquest.com/">MapQuest</a>'
    tiles_subdomains:
        - otile1
        - otile2
        - otile3
        - otile4

    #social networks parameters
    #twitter  https://dev.twitter.com/docs/tweet-button
    social.twitter: true
    social.twitter.locale: '%locale%'
    social.twitter.message: "Un document intéressant : "
    social.twitter.text: 'Tweet'
    social.twitter.via: 'anaphorelabs'
    social.twitter.tag: 'bach' #comma separated
    #g+ - https://developers.google.com/+/web/+1button
    social.gplus: true
    social.gplus.locale: '%locale%'
    social.gplus.size: 'medium' #either small, medium, standard or tall
    social.gplus.annotation: 'bubble' #either none, bubble or inline
    social.gplus.width: '300'
    #facebook - https://developers.facebook.com/docs/plugins/like-button/
    social.fb: true
    social.fb.locale: 'en_US' #either en_US, fr_FR
    social.fb.width: 300
    social.fb.showFaces: false
    social.fb.layout: 'button_count'
    social.fb.share: false

    #supported gettext bundle languages
    gettext.locale_shortcuts:
        en: en_US
        fr: fr_FR

    bach_themes: ['web', 'phone']
    bach_default_theme: 'web'

    #mail parameters (not used for now)
    #mailer_transport: smtp
    #mailer_host: localhost
    #mailer_user: null
    #mailer_password: null

bach_home:
    #Paths to retrieve different types of files
    files:
        videos: '%kernel.root_dir%/../data/videos/'
        musics: '%kernel.root_dir%/../data/musics/'
        misc: '%kernel.root_dir%/../data/files/'
