# Copyright (c) 2014, Anaphore
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     (1) Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#     (2) Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#     (3)The name of the author may not be used to
#    endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

parameters:
    #Main URL. Required for sitemaps
    bach_url: http://localhost

    #database parameters
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: bach
    database_user: bach
    database_password: A_PASSWORD
    database_path: null

    #application locale
    locale: en
    secret: fcfe28f4f96b6167f7e541210b30616ac #To change

    #Solr parameters
    solr_ssl: false
    solr_host: localhost
    solr_port: 8983
    solr_path: /solr
    #Core names for each type
    ead_corename: ead
    matricules_corename: matricules
    #Default search core
    solr_search_core: '%ead_corename%'
    solr_query_fields: ~

    #Path to store uploaded files (from web publication)
    upload_dir: '%kernel.root_dir%/../web/uploads/'

    #Path to files for each type
    ead_files_path: null
    ead_oai_path: null
    matricules_files_path: null
    html_intros_path: null
    images_files_path: null

    ##Features activation
    #main features
    feature.archives: true
    feature.cdc: false
    feature.matricules: false
    feature.expos: false
    feature.browse: true
    #display features
    feature.maps: true
    feature.tagcloud: true
    feature.comments: true
    feature.publication: false
    display.show_maps: true
    display.show_daterange: true
    display.disable_select_daterange: false
    display.rows: 10
    display.show_param: 'list'
    display.ead.rows: '%display.rows%'
    display.ead.show_maps: '%display.show_maps%'
    display.ead.show_daterange: '%display.show_daterange%'
    display.ead.show_param: '%display.show_param%'
    display.matricules.rows: 20
    display.matricules.show_maps: '%display.show_maps%'
    display.matricules.show_daterange: '%display.show_daterange%'
    display.matricules.show_param: '%display.show_param%'
    display.disable_suggestions: false
    display.disable_searchmap: true
    display.ead.result_order: null
    display.disable_connectbutton: false
    display.breadcrumb: true
    matricules_order: null
    cote_location: 'bottom' #either top or bottom
    #other
    feature.openid: false
    feature.social: true
    feature.register: false
    feature.heritage: true
    feature.minify: false
    readingroom: null
    ip_internal: false
    matricules_histogram: 'annee_naissance'
    matricules_listparameters: ['cote', 'date_enregistrement', 'lieu_enregistrement', 'classe', 'nom', 'prenoms', 'matricule', 'annee_naissance', 'lieu_naissance', 'lieu_residence', 'comment']
    matricules_searchparameters: ['cote', 'date_enregistrement', 'lieu_enregistrement', 'classe', 'nom', 'prenoms', 'matricule', 'annee_naissance', 'lieu_naissance', 'lieu_residence', 'comment']
    report_mail: null
    #UI parameters
    viewer_uri: http://viewer.localhost/
    covers_dir: '%kernel.root_dir%/../web/covers/'
    cdc_path: '%kernel.root_dir%/../cdc.xml'
    tiles_url: 'http://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png'
    tiles_attribution: 'donn&eacute;es &copy; <a href="//osm.org/copyright">OpenStreetMap</a>/ODbL - rendu OSM France'
    tiles_subdomains:
        - a
        - b
        - c

    #social networks parameters
    #twitter  https://dev.twitter.com/docs/tweet-button
    social.twitter: true
    social.twitter.locale: '%locale%'
    social.twitter.message: "Un document intéressant : "
    social.twitter.text: 'Tweet'
    social.twitter.via: 'anaphorelabs'
    social.twitter.tag: 'bach' #comma separated
    #g+ - https://developers.google.com/+/web/+1button
    social.gplus: false
    social.gplus.locale: '%locale%'
    social.gplus.size: 'medium' #either small, medium, standard or tall
    social.gplus.annotation: 'bubble' #either none, bubble or inline
    social.gplus.width: '300'
    #facebook - https://developers.facebook.com/docs/plugins/like-button/
    social.fb: false
    social.fb.locale: 'en_US' #either en_US, fr_FR
    social.fb.width: 300
    social.fb.showFaces: false
    social.fb.layout: 'button_count'
    social.fb.share: false
    #scoopit - http://www.scoop.it/install-button
    social.scoopit: true
    social.scoopit.layout: 'horizontal' #either 'horizontal', 'vertical' or 'none'
    minify.providerversion: null
    minify.login: null
    minify.apikey: null

    #supported gettext bundle languages
    gettext.locale_shortcuts:
        en: en_US
        fr: fr_FR

    bach_themes: ['web', 'phone']
    bach_default_theme: 'web'

    default_url: bach_archives
    logo_url: '%default_url%'
    tracker: null
    centerlat: null
    centerlon: null
    zoommap: null
    label.cdc: null
    label.archives: null
    label.matricules: null
    label.expos: null
    label.browse: null
    daodetector: null
    specialeads: null
    cdcdocuments: null
    cdcunlistedfiles: true
    nbrowgenerateimage: 10

    #mail parameters
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    mailer_port: 25
    mailer_encryption: null

    weight.descriptors: 2
    weight.cUnittitle : 1
    weight.parents_titles: 1
    weight.fulltext: 0.1
    weight.cUnitid : 0.1
    collapsecdc: false
    pdf_search: false
    aws.sender: null
    aws.s3.ead_files_path: null
    aws.s3.matricules_files_path: null
    aws.s3.cdc_files_path: null
    aws.s3.bucket: null
    aws.s3: false
    aws.sqs_url: ''
    awsdetect: false
    aws.sqs_nbimages: 10
    cloudfront: null
    print:
       header:
            image: '%kernel.root_dir%/../web/img/smlogo.png'
            content: 'Bach'
       footer:
            image: '%kernel.root_dir%/../web/img/smlogo.png'
            content: '© Anaphore'
bach_home:
    #Paths to retrieve different types of files
    files:
        videos: '%kernel.root_dir%/../data/videos/'
        musics: '%kernel.root_dir%/../data/musics/'
        misc: '%kernel.root_dir%/../data/files/'
    search_forms: ~
#        searchformname: #search form identifier
#            menu_entry: 'My entry' #Will be displayed in main menu
#            query_fields: 'descriptors^2 cUnittitle^1 parents_titles^1 fulltext^0.1' #search query with boost
#            filter: 'headerId:MYID' #will filter query on headerId field. Query is free.

