parameters:
    #Main URL. Required for sitemaps
    bach_url: http://localhost

    #database parameters
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: bach
    database_user: bach
    database_password: A_PASSWORD
    database_path: null

    #application locale
    locale: en
    secret: fcfe28f4f96b6167f7e541210b30616ac #Usefull?

    #Solr parameters
    solr_ssl: false
    solr_host: localhost
    solr_port: 8080
    solr_path: /solr
    #Core names for each type
    ead_corename: ead
    unimarc_corename: unimarc
    matricules_corename: matricules
    #Default search core
    solr_search_core: '%ead_corename%'

    #Path to store uploaded files (from web publication)
    upload_dir: '%kernel.root_dir%/../web/uploads/'

    #Path to files for each type
    ead_files_path: null
    unimarc_files_path: null
    matricules_files_path: null

    ##Features activation
    #main features
    feature.cdc: false
    feature.matricules: false
    feature.expos: false
    #display features
    feature.maps: true
    feature.tagcloud: true
    #other
    feature.openid: false
    feature.social: false

    #UI parameters
    viewer_uri: http://viewer.localhost/
    covers_dir: '%kernel.root_dir%/../web/covers/'
    cdc_path: '%kernel.root_dir%/../cdc.xml'
    client_code: null
    tiles_url: 'http://{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.jpg'
    tiles_attribution: '<a href="http://www.mapquest.com/">MapQuest</a>'
    tiles_subdomains:
        - otile1
        - otile2
        - otile3
        - otile4

    #supported gettext bundle languages
    gettext.locale_shortcuts:
        en: en_US
        fr: fr_FR

    #mail parameters (not used for now)
    #mailer_transport: smtp
    #mailer_host: localhost
    #mailer_user: null
    #mailer_password: null

bach_home:
    #Paths to retrieve different types of files
    files:
        videos: '%kernel.root_dir%/../data/videos/'
        musics: '%kernel.root_dir%/../data/musics/'
        misc: '%kernel.root_dir%/../data/files/'
