administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /

bach_home:
    resource: "@BachHomeBundle/Resources/config/routing.yml"
    prefix:   /

bach_indexation:
    resource: "@BachIndexationBundle/Resources/config/routing.yml"
    prefix:   //

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
