administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /

anph_home:
    resource: "@AnphHomeBundle/Resources/config/routing.yml"
    prefix:   /

anph_indexation:
    resource: "@AnphIndexationBundle/Resources/config/routing.yml"
    prefix:   /
    
upload:
    pattern:  /upload
    defaults: { _controller: AnphIndexationBundle:Default:upload }

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
