administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /administration/

bach_home:
    resource: "@BachHomeBundle/Resources/config/routing.yml"
    prefix:   /

bach_indexation:
    resource: "@BachIndexationBundle/Resources/config/routing.yml"
    prefix:   /indexation/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

sonata_user_profile:
    resource: '@SonataUserBundle/Resources/config/routing/profile.xml'
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fp_openid_security:
    resource: "@FpOpenIdBundle/Resources/config/routing/security.xml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    security_acl: true
    manager_type: orm

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
