jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ARCHIVIST:     ROLE_USER
        ROLE_ADMIN:         [ROLE_USER, ROLE_ARCHIVIST]
        ROLE_SUPER_ADMIN:   [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        openid_user_manager:
            id: bach.home.openid_user_manager
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        secured_area:
            pattern:    ^/
            fp_openid:
                create_user_if_not_exists: true
                provider: openid_user_manager
                required_attributes:
                    - namePerson
                    - namePerson/friendly
                    - namePerson/first
                    - namePerson/last
                    - contact/email
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_openid$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path : ^/indexation, roles: ROLE_ARCHIVIST }

