drivers:
    ead:
        mapper: Anph\IndexationBundle\Entity\Mapper\EADDriverMapper
        fields:
            header:  
                - eadid
                - filedesc/titlestmt/author
                - filedesc/publicationstmt/publisher
                - filedesc/publicationstmt/address/addressline
                - filedesc/publicationstmt/date                
                - profiledesc/langusage/language
            archdesc:
                - did/unitid
                - did/unittitle
                - did/unitdate
                - did/physdesc
                - did/repository
                - did/langmaterial
                - did/origination
                - acqinfo
                - scopecontent
                - accruals
                - arrangement
                - accessrestrict
                - accessrestrict/legalstatus
                - userestrict
                - originalsloc
                - relatedmaterial
                - odd
                - processinfo/processinfo
                - controlaccess
                - dsc
                - dsc/c
                - dsc/c/did/unittitle
                - dsc/c/c/did/unitid
                - dsc/c/c/did/unittitle
                - dsc/c/c/scopcontent
                - dsc/c/c/controlacces