drivers:
    ead:
        mapper: Anph\IndexationBundle\Entity\Mapper\EADDriverMapper
        fields:
            header:  
                - eadid
                - filedesc/titlestmt/author
                - filedesc/publicationstmt/publisher
                - filedesc/publicationstmt/address/addressline
                - filedesc/publicationstmt/date                
                - profiledesc/langusage/language
            archdesc:
                root:
                    - did/unitid
                    - did/unittitle
                    - did/unitdate
                    - did/physdesc
                    - did/repository
                    - did/langmaterial
                    - did/origination
                    - acqinfo
                    - scopecontent
                    - accruals
                    - arrangement
                    - accessrestrict
                    - accessrestrict/legalstatus
                    - userestrict
                    - originalsloc
                    - relatedmaterial
                    - odd
                    - processinfo/processinfo
                    - controlaccess
                c:
                    - did/unittitle
                    - c/did/unitid
                    - c/did/unittitle
                    - scopcontent
                    - controlacces
                    - daogrp/daoloc