fields:
    header:
        - id #Identifiant de l'instrument de recherche
        - author #Auteur(s) de l’instrument de recherche 
        - date #Année de révision, de publication 
        - publisher #Nom de l'éditeur de l'instrument de recherche
        - address #Adresse de l'editeur de l'instrument de recherche
        - language #Langue de l’instrument de recherche 
    
    content:
        - unitid #Cotes, reférences etc...
        - unittitle #Intitulé
        - unitdate #Date
    