parameters:
    administration.xmlimport.class: Bach\AdministrationBundle\Service\XMLImport

services:
    bach.administration.xmlimport:
         class: %administration.xmlimport.class%
         arguments: [ @doctrine.orm.entity_manager ]
